spring:
  datasource:
    url: jdbc:mysql://localhost:3306/duckmelang
    username: root
    password: 1102
  logging:
    level:
      org.springframework: DEBUG
  jwt:
    secret: ZHVja21lbGFuZ2R1Y2ttZWxhbmdkdWNrbWVsYW5nZHVja21lbGFuZw==
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"