spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/duckmelang
    username: root
    password: 1102
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret-key: "duckmelangduckmelangduckmelangduckmelangduckmelang"
  access-expiration: 1800000       #30분
  refresh-expiration: 604800000    #7일