spring:
  jpa:
      show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/duckmelang
    username: root
    password: vn3ew2iv5lzs4!
  logging:
    level:
      org:
        springframework: debug
        hibernate:
          SQL: debug
          type:
            descriptor:
              sql: trace

server:
  port: 8081